# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jackson.serialization.indent_output: true
  cache.type: redis
  redis:
    host: localhost
    port: 6379
security:
  oauth2:
    client:
      client-id: e46ca26359ef71b5285c
      client-secret: 043750121445470d60ad1b43e85b94376f48062b
      accessTokenUri: https://github.com/login/oauth/access_token
      userAuthorizationUri: https://github.com/login/oauth/authorize
      clientAuthenticationScheme: form
    resource:
      userInfoUri: https://api.github.com/user
